# Generated by Django 5.1.6 on 2025-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='aliya_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='army_role_he',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='enlist_reason_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='nickname_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='other_fighting_context_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='previous_last_name_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='release_reason_he',
            field=models.TextField(blank=True, null=True),
        ),
    ]
