# Generated by Django 5.1.3 on 2025-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_country_latitude_country_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='army_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='army_he',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='army_role_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='army_role_he',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
