# Generated by Django 5.1.3 on 2025-06-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0006_alter_soldier_birth_city_en_and_more'),
    ]

    operations = [
    ]
