# Generated by Django 5.1.3 on 2025-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0007_auto_20250610_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
