# Generated by Django 5.1.6 on 2025-04-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name_he', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('first_name_he', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_he', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_city_he', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_city_en', models.CharField(blank=True, max_length=100, null=True)),
                ('army_he', models.CharField(blank=True, max_length=200, null=True)),
                ('army_en', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('participation_he', models.TextField(blank=True, null=True)),
                ('participation_en', models.TextField(blank=True, null=True)),
                ('decorations_he', models.TextField(blank=True, null=True)),
                ('decorations_en', models.TextField(blank=True, null=True)),
                ('biography_he', models.TextField(blank=True, null=True)),
                ('biography_en', models.TextField(blank=True, null=True)),
                ('fighting_description_he', models.TextField(blank=True, null=True)),
                ('fighting_description_en', models.TextField(blank=True, null=True)),
                ('getto_description_he', models.TextField(blank=True, null=True)),
                ('getto_description_en', models.TextField(blank=True, null=True)),
                ('wounds_he', models.TextField(blank=True, null=True)),
                ('wounds_en', models.TextField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_death_he', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_death_en', models.CharField(blank=True, max_length=100, null=True)),
                ('death_details_he', models.TextField(blank=True, null=True)),
                ('death_details_en', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('birth_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldiers', to='mapapp.country')),
            ],
        ),
    ]
