# Generated by Django 5.1.6 on 2025-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_soldier_aliya_date_soldier_army_role_he_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='army_role_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
