# Generated by Django 5.1.3 on 2025-06-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_alter_soldier_army_en_alter_soldier_army_he_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='birth_city_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='birth_city_he',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='first_name_he',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='last_name_he',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='mother_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='nickname_he',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='place_of_death_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='place_of_death_he',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='previous_last_name_he',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
