# Generated by Django 5.1.3 on 2025-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0008_alter_soldier_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
